LECTURE 9 : MACHINE LEARNING
-ML 
    a subseet of all that includes abstruse statistitcal techniques that enable machines to improve at tasks with exp. the category includes deep learning

    -ML system learn how to combine input to predict useful prediction or never-seen data


-VOCABULARY
1. LABEL 
    * the thing we r predicting. FE:
        -the price of the stock
        -the kind of animal in the picture
        -in a simple linear regression : y = a*x + b, the label is Y

2. FEATURE
    * the input variables/ it can be one or several features in ur model. FE:
        -the pixels of an image
        -in a simple linear regression : y = a*x + b, the feature is X


EXAMPLE:
House age(feat) \\\\ Total Rooms(feat) \\\\ House Price(label)

12              \\\\        6        \\\\     200 000$


3. MODEL 
    * the model is the system that define the relationship between the features and the label. HAS TWO PHASES:
        -The training phase(learnin phase)
        -The inference

4. REGRESSION
    * a type of model which predict contin values. FE:
        -the temperature
        -the priice of the stock market

5. CLassification 
    *  a type of model which predict discrete values. FE:
        - the animal on the picture
        -the catefory of a mail9spam or not spam


EXAMPLE:
-Using ML to predict:
    -the success of a movie in cinema
    - the best nxt chess moves
    -the future success of a student
    

THE LEARNING RATE
-the LR is a 


-deep learning




In [1]:
import numpy as np


In [5]:
# create ur first 2 dimensionnal array
l = ([1,2,3],[4,5,6])
array = np.array([[1,2,3],[4,5,6]])
print(array)
print("-"*20)
print(l)

[[1 2 3]
 [4 5 6]]
--------------------
([1, 2, 3], [4, 5, 6])


In [7]:
#  copy, view
list0 = [1,2,3]
list1 = list0.copy()
list1[0] =55
print(list1)
print(list0)

[55, 2, 3]
[1, 2, 3]


In [9]:
arr = np.array([1,2,3])
arr0 = arr
arr1  = arr0.view()
arr2=arr0.copy()
arr1[1]=50
arr2[1]=50000
print(arr0)
print(arr1)
print(arr2)


[ 1 50  3]
[ 1 50  3]
[    1 50000     3]


In [17]:
# shape of an array
array = np.array([1,2,3,4,5,6])
print(array.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [16]:
# shape of an array
array = np.array([[1,2,3],[4,5,6]])
print(array.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [24]:
# shape of an array
array = np.array([1,2,3,4,5,6])
print(array.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [28]:
array= np.array([1,5,9,31,45,78])
print(array.reshape(-1,2))

[[ 1  5]
 [ 9 31]
 [45 78]]


In [1]:
import numpy as np;
Input1 = input.s
Input2 = input.split()
arr = np.c_[[Input1],[Input2]]
print(arr.reshape((len(arr)/2),2))

AttributeError: 'function' object has no attribute 'split'